### ISSUE TITLE
Prepare for 1.0 release

### ISSUE THREAD

**Issue by 486c** [486c/rosu-memory#31]
- [x] #20 
- [x] #30 
- [x] #17
- [x] Benchmark reading loop & static addresses loop and document result's into README
- [x] Document changes about osu! folder auto-detection
- [x] Port counters that use map background
- [x] Port counters that have map progress in it

**Comment by 486c** [comment]
Feel free to discuss & add something that you think should be present in 1.0 release

**Comment by S1n1st3rn3ss** [comment]
I think a slight change to json structure (and `Values`) are warranted as the current form of it is a bit too clunky:

- Move pp and sr to separate structs (because I plan on adding 100-95% acc pp calculation later on, as well as gradual sr calculation, and having many pp/sr values in main struct would be bad UX for overlay creation)
- @uzervlad wanted to get Bancho data to a usable state, and that would create some overlaps (specifically username, might be more than that)
- Similar issue might happen if we start storing pre- and post-mod map stats like AR/CS and BPM, so splitting song select stuff from gameplay data could be handy
- Implementing some struct methods would make more sense this way

I might be missing downsides but in general a slight refactor of `Values` seems like a nice thing to do (if we agree on what should go where)
